### ISSUE TITLE
Always provide link to WorkItem report 

### ISSUE THREAD

**Issue by adamenagy** [Autodesk-Forge/forge-configurator-inventor#350]
At the moment you only get a link to the report if the WorkItem failed to update the model.
However, the update being "successful" does not mean it was "as expected" or "correct". 
Best thing is to make the report always available.

**Comment by hradilm** [comment]
Hello Adam. Thank for your feedback. We will review this request and let you know if we add it to the plan for future development.

**Comment by thickiran** [comment]
Guys i've been checking the progress for a while, do you think we are ready to get our c360 files into this?

**Comment by mivasi** [comment]
Hi @thickiran, feel free to try out. The more feedback we will have, the better. Until November 20 you are able to use our deployed version http://inventor-config-demo.autodesk.io/. You can log in and try to upload your designs. After November 20. you have to run our application on your local computer, which should be really easy to try out.

**Comment by hradilm** [comment]
Hello Adam. This enhancement is now finished and deployed to our application. Feel free to try it out.
