### ISSUE TITLE
Embedded Mode truncating URL

### ISSUE THREAD

**Issue by JustinRice1998** [Autodesk-Forge/forge-configurator-inventor#396]
Running the embedded mode the following url was passed in: https://subseaxd-staging.mcdermott.com/api/pri/v1/configurator/project/600a6937e498fd4f20e666ec?projectId=-M73LyZXYLoHZk6j-ms3&subProjectId=-M73MRx2visv8-KjjmWX&assetId=-MQt6umRXpy29G1NyOMF

However the console reported the following:
2021-02-02 13:50:18.707 +00:00 [INF] downloading parameters from https://subseaxd-staging.mcdermott.com/api/pri/v1/configurator/project/600a6937e498fd4f20e666ec?projectId=-M73LyZXYLoHZk6j-ms3

What would cause this url to be truncated? It appears to be truncating at the &.

**Comment by mivasi** [comment]
You should encode url before putting it inside url parameter. For example your URL encoded looks like this
`"https%3A%2F%2Fsubseaxd-staging.mcdermott.com%2Fapi%2Fpri%2Fv1%2Fconfigurator%2Fproject%2F600a6937e498fd4f20e666ec%3FprojectId%3D-M73LyZXYLoHZk6j-ms3%26subProjectId%3D-M73MRx2visv8-KjjmWX%26assetId%3D-MQt6umRXpy29G1NyOMF"`

In javascript you can encode urls using encodeURIComponent https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent
