### ISSUE TITLE
how to get started with my own inventor files?

### ISSUE THREAD

**Issue by mogmedia** [Autodesk-Forge/forge-configurator-inventor#406]
Hey,

i have some problems to get my own inventor files up and running.
I tried to adjust the /appsettings.json 
`"DefaultProjects": {
    "Projects": [
      {
        "Url": "https://sdra-default-projects.s3.us-west-2.amazonaws.com/WrenchForm.zip",
        "TopLevelAssembly": "Wrench.iam",
        "Name": "Wrench"
      },
      {
        "Url": "https://sdra-default-projects.s3.us-west-2.amazonaws.com/Wheel_multi_IDW.zip",
        "TopLevelAssembly": "WheelAssembly.iam",
        "Name": "Wheel"
      }
    ]
  },`

and replaced the links, TopLevelAssembly and Names with my files but they never appear in the Webapp!

How can I get this to work? 
Thanks

**Comment by hradilm** [comment]
Hello. 

In order populate the app with the Default projects (which is I believe, what you are trying to accomplish) you need to initialize the application as described here https://github.com/Autodesk-Forge/forge-configurator-inventor#clear-and-load-initial-data-during-app-launch-time. Please be aware that this step is going to clear entire OSS content.

Another option to get your Inventor design to the app is to use the application UI to upload it there. First you need to enable public authentication by setting value on this line https://github.com/Autodesk-Forge/forge-configurator-inventor/blob/960c81a246cfa1d6f54296f3f729f748a6fbfd33/WebApplication/appsettings.json#L37 to `false` and then you need to sign-in yourself in the application UI (click the icon with Autodesk logon in the top right corner of the screen) and then you can hit the `Upload package` button on the `Projects` tab.
