### ISSUE TITLE
Unable to run App From Source

### ISSUE THREAD

**Issue by prefabking** [Autodesk-Forge/forge-configurator-inventor#407]
Hi,

I'm trying to run the app from the source but not able to run successfully. I followed all the instructions mentioned on GitHub. It doesn't do anything after the below line for a long time:
![image](https://user-images.githubusercontent.com/53575056/116849569-520f2a80-ac32-11eb-982f-f39522654565.png)

Any help is appreciated.

**Comment by hradilm** [comment]
Hello,

  have you try to open the internet browser and navigate to the page https://localhost:5001 ?

Michal

**Comment by tourvangroup** [comment]
Thanks @hradilm for your reply. Yes did that already browser opens automatically but nothing happens for a long time. Any other thoughts?

**Comment by tourvangroup** [comment]
This issue has seemed to have rectified itself & i can get to home screen. When logging in i get the forge authorize application & then login failed image. any suggestions would be appreciated
![Screen Shot](https://user-images.githubusercontent.com/53575056/116965143-7af5f500-acf0-11eb-9539-83b38a3b8495.PNG)

**Comment by mivasi** [comment]
Hello,

you just modify the value inside the config, see https://github.com/Autodesk-Forge/forge-configurator-inventor/blob/master/WebApplication/appsettings.json#L36

You can change `Enable: true` to `Enable: false`

You can do it directly in appsettings.json file, or you can do override in your appsetting.Local.json

**Comment by prefabking** [comment]
@mivasi @hradilm Thanks for your help! greatly appreciated
