### ISSUE TITLE
Access to this site is by invitation only. Your email is not authorized.

### ISSUE THREAD

**Issue by barsham** [Autodesk-Forge/forge-configurator-inventor#413]
When I tried to login to your site with my Forge account, I got below error.

Access to this site is by invitation only. Your email is not authorized.

site:
[https://inventor-config-demo.autodesk.io/](https://inventor-config-demo.autodesk.io/)

![image](https://user-images.githubusercontent.com/5785864/124603163-fb7dd100-deac-11eb-94b0-c47a0aaf465e.png)

**Comment by thickiran** [comment]
forge-configurator-inventor/WebApplication/appsettings.json
  
  "InviteOnlyMode": {
    "Enabled": true,
    "Domains": [ "autodesk.com" ],
    "Addresses": [ "adsk.demo.tool@gmail.com", "adsk.demo.tool+0@gmail.com" ]
  },

master code has this, so clone it and change the "Enabled":true, to false

**Comment by barsham** [comment]
Thanks @thickiran that's what I was thinking as a workaround too.
