### ISSUE TITLE
Download DWG

### ISSUE THREAD

**Issue by daitam** [Autodesk-Forge/forge-configurator-inventor#415]
What should be the correct approach to add an option for exporting DWG from IDW?

**Comment by mivasi** [comment]
Hi,
you can write new appbundle and use it in the application. You can look at some hints here
https://github.com/Autodesk-Forge/forge-configurator-inventor/wiki/How-to-add-new-Inventor-plugin

**Comment by daitam** [comment]
> Hi,
> you can write new appbundle and use it in the application. You can look at some hints here
> https://github.com/Autodesk-Forge/forge-configurator-inventor/wiki/How-to-add-new-Inventor-plugin

Thanks for the link. I've in progress with creating an AppBundle for DWG export. I Will share it here when I'm done, maybe someone will find it useful.

**Comment by daitam** [comment]
[DWGExportPlugin.zip](https://github.com/Autodesk-Forge/forge-configurator-inventor/files/6871588/DWGExportPlugin.zip)

Created DWG export app bundle heavily based on existing RFA and PDF export bundles.

**Comment by Nicoleitru** [comment]
Hi @daitam, I am wondering if you could provide insight as to how you successfully imported this plugin into the project. After importing, the project builds, however when I try initializing everything, I either get an error or the export DWG functionality is not present on the web page.
