### ISSUE TITLE
Can not upload zip or ipt any file

### ISSUE THREAD

**Issue by KadirHaktan** [Autodesk-Forge/forge-configurator-inventor#479]
Hello!When i try to upload ipt file got this error:**System.Net.Http.HttpRequestException: 'The server returned the non-success status code 400 (Bad Request).
More error details:
{"activityId":["The activity FcuaA6cCAKd9jv7vmVBAcG8bR9NUZgBA.AdoptProject+alpha could not be found (Parameter 'activityId')"]}.'**

I think design automation can not create or find activityId
<img width="620" alt="screen1" src="https://user-images.githubusercontent.com/38834423/230023392-85805c0c-cad3-4e88-be03-186477f21d75.png">
await ProjectWork.AdoptAsync(_projectInfo,signedUploadedUrl) method can not give success response and exception image is under below
<img width="1049" alt="screen2" src="https://user-images.githubusercontent.com/38834423/230023755-a334187e-feca-42ce-bd2c-4cf13308f939.png">

**Comment by mivasi** [comment]
Hi, have you done `dotnet run initialize=true`

Activites are created during initialization which should be done once with first run.

FYI: this repo is going to be deprecated as we are moving to https://github.com/autodesk-platform-services/aps-configurator-inventor

**Comment by KadirHaktan** [comment]
Solved
