### ISSUE TITLE
When i open to configurator from mobile device,Viewer's right side is white empty

### ISSUE THREAD

**Issue by KadirHaktan** [Autodesk-Forge/forge-configurator-inventor#480]
Hello everyone!Hope you can help to me!My problem is actually mobile device view and view's problem is about to when first time open to my configurator website,A white space is being created on the right side of the viewer area.I don not know why and i tried to CSS's media query codes and something like these.But can not solve this view's problem.And there is a video

Meanwhile, i removed to some components on React view ui as you can see.But css or js codes did not change so much

https://github.com/Autodesk-Forge/forge-configurator-inventor/assets/38834423/cd45b2f4-1e77-4ecd-bfb3-f6089c117399

**Comment by mivasi** [comment]
Hello Kadir,

I am afraid we cannot help you there. We didn't optimize the app for mobile device. The goal of the app was to show how to build configurator on top of the APS Design Automation system. Further customization needs to be done by end users of the code.
